# Generated by Django 2.1.2 on 2018-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='activeEmail_status',
            field=models.BooleanField(default=False),
        ),
    ]
