# Generated by Django 2.1.2 on 2018-10-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryItemMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimedia', models.FileField(upload_to='multimedia')),
                ('order', models.PositiveIntegerField()),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Memory')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryItemText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000000000)),
                ('order', models.PositiveIntegerField()),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Memory')),
            ],
        ),
    ]
