# Generated by Django 2.1.2 on 2018-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
