# Generated by Django 2.1.2 on 2018-10-27 13:43

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_memory_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PointLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='numlikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='post.MemoryComment'),
        ),
        migrations.AddField(
            model_name='memory',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='post.MemoryTag'),
        ),
    ]
