# Generated by Django 2.1.2 on 2018-10-29 15:01

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181027_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionedTimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PathLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PointMentionedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('century', models.IntegerField(blank=True, null=True)),
                ('decade', models.IntegerField(blank=True, choices=[(1, '10s'), (2, '20s'), (3, '30s'), (4, '40s'), (5, '50s'), (6, '60s'), (7, '70s'), (8, '80s'), (9, '90s'), (0, '00s')], null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Jenuary'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'December'), (12, 'November')], null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('day_name', models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True)),
            ],
        ),
        migrations.AddField(
            model_name='memory',
            name='pointlocations',
            field=models.ManyToManyField(to='post.PointLocation'),
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='comments',
            field=models.ManyToManyField(to='post.MemoryComment'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='tags',
            field=models.ManyToManyField(to='post.MemoryTag'),
        ),
        migrations.AlterField(
            model_name='pointlocation',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='pathlocation',
            name='location_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='post.PointLocation'),
        ),
        migrations.AddField(
            model_name='pathlocation',
            name='location_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='post.PointLocation'),
        ),
        migrations.AddField(
            model_name='mentionedtimeperiod',
            name='time_begin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='post.PointMentionedTime'),
        ),
        migrations.AddField(
            model_name='mentionedtimeperiod',
            name='time_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='post.PointMentionedTime'),
        ),
        migrations.AddField(
            model_name='memory',
            name='mentioned_time',
            field=models.ManyToManyField(to='post.PointMentionedTime'),
        ),
        migrations.AddField(
            model_name='memory',
            name='mentioned_time_period',
            field=models.ManyToManyField(to='post.MentionedTimePeriod'),
        ),
        migrations.AddField(
            model_name='memory',
            name='pathlocations',
            field=models.ManyToManyField(to='post.PathLocation'),
        ),
    ]
