# Generated by Django 2.1.2 on 2018-11-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20181029_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='tags',
        ),
        migrations.AddField(
            model_name='memorycomment',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Memory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memorytag',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Memory'),
            preserve_default=False,
        ),
    ]
