# Generated by Django 2.1.2 on 2018-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20181110_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='mentioned_time',
            field=models.ManyToManyField(blank=True, to='post.PointMentionedTime'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='mentioned_time_period',
            field=models.ManyToManyField(blank=True, to='post.MentionedTimePeriod'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='pathlocations',
            field=models.ManyToManyField(blank=True, to='post.PathLocation'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='pointlocations',
            field=models.ManyToManyField(blank=True, to='post.PointLocation'),
        ),
    ]
