# Generated by Django 2.1.2 on 2018-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20181110_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorycomment',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='memorytag',
            name='memory',
        ),
        migrations.AddField(
            model_name='memory',
            name='comments',
            field=models.ManyToManyField(blank=True, to='post.MemoryComment'),
        ),
        migrations.AddField(
            model_name='memory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='post.MemoryTag'),
        ),
    ]
