# Generated by Django 2.1.2 on 2018-11-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registereduser_activeemail_status'),
        ('post', '0008_auto_20181110_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_user', to='login.RegisteredUser'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.RegisteredUser'),
        ),
    ]
