# Generated by Django 2.1.2 on 2018-11-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registereduser_activeemail_status'),
        ('post', '0009_auto_20181110_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.RegisteredUser'),
            preserve_default=False,
        ),
    ]
