# Generated by Django 2.0.6 on 2018-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_memorycomment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to='login.RegisteredUser'),
        ),
    ]
