# Generated by Django 2.0.6 on 2018-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20181113_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryitemmultimedia',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'image'), (2, 'video'), (3, 'audio')], default=1),
            preserve_default=False,
        ),
    ]
