# Generated by Django 2.0.6 on 2018-11-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_memorymultimediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorymultimediaupload',
            name='photo',
        ),
        migrations.AddField(
            model_name='memorymultimediaupload',
            name='media',
            field=models.FileField(default=1, upload_to='memory_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memorymultimediaupload',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'image'), (2, 'video'), (3, 'audio')], default=1),
            preserve_default=False,
        ),
    ]
