# Generated by Django 2.0.6 on 2018-11-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20181124_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryitemmultimedia',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.MemoryMultimediaUpload'),
        ),
    ]
