# Generated by Django 2.1.2 on 2018-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20181125_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointmentionedtime',
            name='decade',
            field=models.IntegerField(blank=True, choices=[(1, '1910s'), (2, '1920s'), (3, '1930s'), (4, '1940s'), (5, '1950s'), (6, '1960s'), (7, '1970s'), (8, '1980s'), (9, '1990s'), (0, '1900s')], null=True),
        ),
    ]
