# Generated by Django 2.1.2 on 2018-12-14 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20181213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycomment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
