# Generated by Django 2.1.2 on 2018-12-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_memorycomment_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentionedtimeperiod',
            name='time_begin',
        ),
        migrations.RemoveField(
            model_name='mentionedtimeperiod',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='mentioned_time_period',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='century',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='day',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='day_name',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='decade',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='month',
        ),
        migrations.RemoveField(
            model_name='pointmentionedtime',
            name='year',
        ),
        migrations.AddField(
            model_name='pointmentionedtime',
            name='date_format',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointmentionedtime',
            name='date_string1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointmentionedtime',
            name='date_string2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pointmentionedtime',
            name='date_type',
            field=models.IntegerField(choices=[(0, 'single'), (1, 'period')], default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='memory',
            name='mentioned_time',
        ),
        migrations.AddField(
            model_name='memory',
            name='mentioned_time',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='post.PointMentionedTime'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MentionedTimePeriod',
        ),
    ]
