# Generated by Django 2.1.2 on 2018-12-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20181221_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='mentioned_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PointMentionedTime'),
        ),
    ]
