# Generated by Django 2.1.2 on 2018-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20181224_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pointlocation',
            name='location_coordinates',
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='location_coordinate_latitude',
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='location_coordinate_longitude',
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='location_name',
            field=models.CharField(default=str, max_length=30),
            preserve_default=False,
        ),
    ]
