# Generated by Django 2.1.2 on 2019-01-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20181231_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.IntegerField(choices=[(0, 'separate'), (1, 'path')]),
        ),
    ]
