# Generated by Django 2.1.2 on 2019-01-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0008_auto_20190101_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=50)),
                ('a_type', models.CharField(max_length=50)),
                ('motivation', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.RegisteredUser')),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=70)),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Selector')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Body'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Creator'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Target'),
        ),
    ]
