# Generated by Django 2.1.2 on 2018-11-23 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_registereduser_activeemail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile_photos')),
            ],
        ),
        migrations.AddField(
            model_name='registereduser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, "Other/Don't want to say")], null=True),
        ),
        migrations.AddField(
            model_name='profilephotos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.RegisteredUser'),
        ),
    ]
