# Generated by Django 2.1.2 on 2018-11-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181123_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='profile_photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.RegisteredUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='profilephotos',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfilePhotos',
        ),
    ]
