# Generated by Django 2.1.2 on 2018-12-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
