# Generated by Django 2.0.6 on 2018-11-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
