# Generated by Django 2.1.2 on 2019-01-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_registereduser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('location_coordinate_latitude', models.CharField(max_length=30)),
                ('location_coordinate_longitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='registereduser',
            name='advanced_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.PointLocation'),
        ),
    ]
